### ISSUE TITLE
Not compatible with WebStorm 2017

### ISSUE THREAD

**Issue by hongbo-miao** [ngehlert/cobalt2#1]
First thanks!
However, I tried it yesterday. It does not compatible with WebStorm 2017. Failed to import the settings.

**Comment by ngehlert** [comment]
well i have the newest version 2017.2 :D what version do you use? is there a problem importing the file? do you get an error? @Hongbo-Miao 

edit: i just tried it with a freshly installed version and it worked fine. Preference --> Edit --> Color Scheme --> then the small gear-wheel --> import scheme

**Comment by hongbo-miao** [comment]
weird, same version, i will try again. maybe my step is wrong.

**Comment by hongbo-miao** [comment]
Cool, works!

**Comment by ngehlert** [comment]
awesome nice:)
@Hongbo-Miao can you update your steps at https://github.com/wesbos/cobalt2/issues/85#issuecomment-319202355 ?
did you do anything different? was my documentation unclear?

**Comment by hongbo-miao** [comment]
Just like you said: Preference --> Edit --> Color Scheme --> then the small gear-wheel --> import scheme.

Before somehow I have three java files instead of cobalt2.icls, I might mix up with another one.

**Comment by FelipeLujan** [comment]
it's not working for me on webstorm 2018.1. Any idea?

**Comment by ngehlert** [comment]
@FelipeLujan  well it's hard to help with no further information :) what did you try? I tested with 2018.1 and it worked fine. 
Do you get any error message? What OS are you working on?

**Comment by FelipeLujan** [comment]
oh, sorry for such poor report.

the error i'm getting is: **not a valid scheme**, running webstorm 2018.1 on ubuntu 16.04

**Comment by ngehlert** [comment]
@FelipeLujan I added a 	added color scheme plugin jar file. Can you try to download it and install it. maybe it works with this one.
Webstorm --> Preference --> Plugin --> Install Plugin from disk.
On a side note, I also submitted the plugin to Jetbrains but it take 1-2 days until approved. So you can also wait and install it then over their repository.

**Comment by ngehlert** [comment]
@FelipeLujan also available now over the official plugin repository. let me know if you still have problems
https://plugins.jetbrains.com/plugin/10745-cobalt-2-color-scheme

**Comment by FelipeLujan** [comment]
Thanks.  at the end of the day I was able to use it but I preferred one of the default themes.
Thanks a lot!
