### ISSUE TITLE
Any plans for a full theme?

### ISSUE THREAD

**Issue by djensen47** [ngehlert/cobalt2#2]
Thanks for porting Cobalt2 to IntelliJ!

Do you have any plans to make this a full theme on top of the existing editor color scheme? I can't seem to find any UI themes that pair well with the blue Cobalt2 editor.

Thanks again!

**Comment by ngehlert** [comment]
@djensen47 Hi thanks for the feedback. 
I don't quite understand your question, do you mean for example top bar and file window? (Selectable with Preferences --> Appearance & Behavior --> Appearance --> Theme)

Is it possible to add custom themes there? I use it in combination with the Light theme, I like having the file window on a white background.

I will check if I can modify those colors as well and include them in the Theme plugin

**Comment by djensen47** [comment]
It would be great to have the Cobalt2 colors for all of the UI in IntelliJ, not just the editor. Thanks!

**Comment by ngehlert** [comment]
just saw that it is possible since 2019.1 to create custom UI Themes. Definitely will add it as soon as possible :)

**Comment by ngehlert** [comment]
@djensen47 should be available within a week

**Comment by ngehlert** [comment]
theme is out. just update your current Cobalt 2 plugin and select the UI theme in Appearance.
Let me know how you like it. I'm not quite happy with all the colors, so expect some minor changes in the near future, but I wanted to get it published ASAP to get some feedback :)
