### ISSUE TITLE
Please add support for .mdx file format

### ISSUE THREAD

**Issue by stevensacks** [ngehlert/cobalt2#3]
Cobalt2 does not currently support the `.mdx` file format.

WebStorm added support for the .mdx file format in v2020.1.
https://youtrack.jetbrains.com/issue/WEB-32599#focus=streamItem-27-4091257.0-0

Other default themes support it so it's possible that all you need to do is copy/paste some values. I'm not exactly sure how it works.

**Comment by ngehlert** [comment]
I'll have a look @stevensacks

**Comment by stevensacks** [comment]
Thanks!

**Comment by ngehlert** [comment]
@stevensacks just wanted to let you know I haven't forgotten this request. Still looking into it. I just haven't quite figured out yet what config values I need to adjust.

I'll keep you updated

**Comment by ngehlert** [comment]
well I just can't get it to work. Tried to contact jetbrains on multiple channels for assistance but haven't received an answer yet
https://youtrack.jetbrains.com/issue/WEB-32599#focus=Comments-27-4247053.0-0
I'll keep you updated

**Comment by stevensacks** [comment]
Sorry to have let this go so long. It’s definitely working now. I’ll close the issue.
